[package]
name = "tun2proxy"
version = "0.2.12"
edition = "2021"
license = "MIT"
repository = "https://github.com/blechschmidt/tun2proxy"
homepage = "https://github.com/blechschmidt/tun2proxy"
authors = ["B. Blechschmidt", "ssrlive"]
description = "Tunnel interface to proxy"
readme = "README.md"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
async-recursion = "1.0"
async-trait = "0.1"
base64 = { version = "0.22" }
chrono = "0.4"
clap = { version = "4.5", features = ["derive", "wrap_help", "color"] }
ctrlc2 = { version = "3.5", features = ["tokio", "termination"] }
digest_auth = "0.3"
dotenvy = "0.15"
env_logger = "0.11"
hashlink = "0.9"
httparse = "1.8"
ipstack = { version = "0.0", features = ["log"] }
log = { version = "0.4", features = ["std"] }
socks5-impl = { version = "0.5" }
thiserror = "1.0"
tokio = { version = "1.36", features = ["full"] }
tokio-util = "0.7"
tproxy-config = { version = "2.0", features = ["log"] }
trust-dns-proto = "0.23"
tun2 = { version = "1.2", features = ["async"] }
udp-stream = { version = "0.0", default-features = false }
unicase = "2.7"
url = "2.5"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13"
jni = { version = "0.21", default-features = false }

[build-dependencies]
serde_json = "1.0"
winres = "0.1.12"

[[bin]]
name = "gpm_proxy_as_vpn"
path = "src/bin/main.rs"
